### ISSUE TITLE
input[type="search"] box-sizing is content-box when used with normalize.css

### ISSUE THREAD

**Issue by dhensby** [inuitcss/generic.box-sizing#2]
Search inputs are forced to `box-sizing: content-box` by normalize.css and the rules in this component are not specific enough (in that instance) to set it to `border-box`

**Comment by csshugs** [comment]
@dhensby 
It can't be made more specific in this module.
Your issue is addressed [in the appropriate repo](https://github.com/inuitcss/generic.normalize/issues/8) , though. So maybe this can be closed?

**Comment by dhensby** [comment]
Has the issue been addressed or just opened?

**Comment by csshugs** [comment]
> I'd merge a patch for this normalize issue; agree that it's annoying / wrong.
    — necolas

Well, OK, just opened :P 

But anyways, it's not a bug with this repo but rather with normalize.css

**Comment by csshugs** [comment]
[See here](https://github.com/necolas/normalize.css/issues/471) for the referencing issue in the normalize.css repo.

**Comment by dhensby** [comment]
Once https://github.com/necolas/normalize.css/pull/496 is merged, this should be fixed

**Comment by dhensby** [comment]
I think this repo still needs to override that input type depending on whether we use border box or not... So isn't a patch needed anyway?

**Comment by csshugs** [comment]
> I think this repo still needs to override that input type

Well yeah, in case we don't use border-box, that declaration for `input[type=search]` in normalize must be overridden. But not via this module. This is a generic module which sets everything to `border-box`. If you don't want global `border-box` (and who really wants that, honestly?) you just don't use this module in your project.

Ideally, the patch for that line in normalize.css would be to not declaring any `box-sizing` at all. With that, we'd had no problem at all with our issue.

The generel problem here, howsoever we twist it, is that we are using a third party module (normalize.css). It's difficult to deal with it either way.

**Comment by csshugs** [comment]
@anselmh @dhensby 
This is fixed [in the normalize repo](https://github.com/inuitcss/generic.normalize/pull/10)
